import type { CollegeIdentity } from '../models/collegeIdentity.js';
import { CollegeStatus } from '../models/collegeStatus.js';

export const collegeSeedData: readonly CollegeIdentity[] = [
  {
    id: 'coep-pune',
    officialName: 'COEP Technological University',
    shortName: 'COEP',
    aliases: ['College of Engineering Pune', 'COEP Pune', 'College of Engineering, Pune'],
    knownDomains: ['coep.org.in'],
    officialWebsite: 'https://www.coep.org.in/',
    city: 'Pune',
    district: 'Pune',
    state: 'Maharashtra',
    university: 'COEP Technological University',
    collegeType: 'government',
    autonomous: true,
    knownKeywords: ['COEP', 'College of Engineering Pune', 'engineering', 'Pune', 'Shivajinagar'],
    status: CollegeStatus.ACTIVE,
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  },
  {
    id: 'vjti-mumbai',
    officialName: 'Veermata Jijabai Technological Institute',
    shortName: 'VJTI',
    aliases: ['VJTI Mumbai', 'Victoria Jubilee Technical Institute', 'VJTI, Mumbai'],
    knownDomains: ['vjti.ac.in'],
    officialWebsite: 'https://vjti.ac.in/',
    city: 'Mumbai',
    district: 'Mumbai',
    state: 'Maharashtra',
    university: 'University of Mumbai',
    collegeType: 'government',
    autonomous: true,
    knownKeywords: ['VJTI', 'Veermata Jijabai', 'Mumbai', 'engineering', 'Matunga'],
    status: CollegeStatus.ACTIVE,
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  },
  {
    id: 'spit-mumbai',
    officialName: 'Sardar Patel Institute of Technology',
    shortName: 'SPIT',
    aliases: ['SPIT Mumbai', 'Sardar Patel', 'SPIT, Andheri'],
    knownDomains: ['spit.ac.in'],
    officialWebsite: 'https://www.spit.ac.in/',
    city: 'Mumbai',
    district: 'Mumbai',
    state: 'Maharashtra',
    university: 'University of Mumbai',
    collegeType: 'private',
    autonomous: true,
    knownKeywords: ['SPIT', 'Sardar Patel', 'Andheri', 'Mumbai', 'engineering'],
    status: CollegeStatus.ACTIVE,
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  },
  {
    id: 'djsce-mumbai',
    officialName: 'Dwarkadas J. Sanghvi College of Engineering',
    shortName: 'DJSCE',
    aliases: ['DJSCE Mumbai', 'Sanghvi College', 'D. J. Sanghvi'],
    knownDomains: ['djsce.ac.in'],
    officialWebsite: 'https://www.djsce.ac.in/',
    city: 'Mumbai',
    district: 'Mumbai',
    state: 'Maharashtra',
    university: 'University of Mumbai',
    collegeType: 'private',
    autonomous: true,
    knownKeywords: ['DJSCE', 'Dwarkadas Sanghvi', 'Vile Parle', 'Mumbai', 'engineering'],
    status: CollegeStatus.ACTIVE,
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  },
  {
    id: 'tsec-mumbai',
    officialName: 'Thadomal Shahani Engineering College',
    shortName: 'TSEC',
    aliases: ['TSEC Bandra', 'Thadomal Shahani', 'Thadomal Shahani, Bandra'],
    knownDomains: ['tsec.ac.in'],
    officialWebsite: 'https://www.tsec.ac.in/',
    city: 'Mumbai',
    district: 'Mumbai',
    state: 'Maharashtra',
    university: 'University of Mumbai',
    collegeType: 'private',
    autonomous: true,
    knownKeywords: ['TSEC', 'Thadomal Shahani', 'Bandra', 'Mumbai', 'engineering'],
    status: CollegeStatus.ACTIVE,
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  },
  {
    id: 'vesit-mumbai',
    officialName: "Vivekanand Education Society's Institute of Technology",
    shortName: 'VESIT',
    aliases: ['VESIT Mumbai', 'Vivekanand Education Society', 'VESIT, Chembur'],
    knownDomains: ['vesit.ac.in'],
    officialWebsite: 'https://vesit.ves.ac.in/',
    city: 'Mumbai',
    district: 'Mumbai',
    state: 'Maharashtra',
    university: 'University of Mumbai',
    collegeType: 'private',
    autonomous: true,
    knownKeywords: ['VESIT', 'Vivekanand Education Society', 'Chembur', 'Mumbai', 'engineering'],
    status: CollegeStatus.ACTIVE,
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  },
  {
    id: 'kjsce-mumbai',
    officialName: 'K. J. Somaiya College of Engineering',
    shortName: 'KJSCE',
    aliases: ['KJSCE Mumbai', 'Somaiya College of Engineering', 'K. J. Somaiya'],
    knownDomains: ['kjsce.somaiya.edu'],
    officialWebsite: 'https://kjsce.somaiya.edu/',
    city: 'Mumbai',
    district: 'Mumbai',
    state: 'Maharashtra',
    university: 'Somaiya Vidyavihar University',
    collegeType: 'private',
    autonomous: true,
    knownKeywords: ['KJSCE', 'Somaiya', 'Vidyavihar', 'Mumbai', 'engineering'],
    status: CollegeStatus.ACTIVE,
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  },
  {
    id: 'pict-pune',
    officialName: 'Pune Institute of Computer Technology',
    shortName: 'PICT',
    aliases: ['PICT Pune', 'Pune Institute of Computer Technology', 'PICT, Dhankawadi'],
    knownDomains: ['pict.edu'],
    officialWebsite: 'https://pict.edu/',
    city: 'Pune',
    district: 'Pune',
    state: 'Maharashtra',
    university: 'Savitribai Phule Pune University',
    collegeType: 'private',
    autonomous: true,
    knownKeywords: ['PICT', 'Pune Institute', 'Dhankawadi', 'Pune', 'computer', 'engineering'],
    status: CollegeStatus.ACTIVE,
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  },
  {
    id: 'pccoe-pune',
    officialName: 'Pimpri Chinchwad College of Engineering',
    shortName: 'PCCOE',
    aliases: ['PCCOE Pune', 'Pimpri Chinchwad', 'PCCOE, Nigdi'],
    knownDomains: ['pccoepune.com'],
    officialWebsite: 'https://www.pccoepune.com/',
    city: 'Pune',
    district: 'Pune',
    state: 'Maharashtra',
    university: 'Savitribai Phule Pune University',
    collegeType: 'private',
    autonomous: true,
    knownKeywords: ['PCCOE', 'Pimpri Chinchwad', 'Nigdi', 'Pune', 'engineering'],
    status: CollegeStatus.ACTIVE,
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  },
  {
    id: 'wce-sangli',
    officialName: 'Walchand College of Engineering',
    shortName: 'WCE',
    aliases: ['WCE Sangli', 'Walchand Sangli', 'Walchand College of Engineering, Sangli'],
    knownDomains: ['walchandsangli.ac.in'],
    officialWebsite: 'https://www.walchandsangli.ac.in/',
    city: 'Sangli',
    district: 'Sangli',
    state: 'Maharashtra',
    university: 'Shivaji University',
    collegeType: 'government',
    autonomous: true,
    knownKeywords: ['WCE', 'Walchand', 'Sangli', 'engineering', 'government'],
    status: CollegeStatus.ACTIVE,
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    updatedAt: new Date('2024-01-01T00:00:00.000Z'),
  },
];
